name: linksHub
description: App Flutter para CRUD de links de redes sociais

publish_to: 'none'

version: 1.0.0+1

environment:
  # Atualize para >=3.0.0 se seu Flutter/Dart já for 3.x
  sdk: '>=2.19.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Banco local
  sqflite: ^2.3.0
  path: ^1.8.3
  path_provider: ^2.0.15 # recomendado para localizar diretórios
  url_launcher: ^6.1.12

  # Ícones sociais
  font_awesome_flutter: ^10.5.0
  cupertino_icons: ^1.0.5 # boa prática adicionar
  flutter_launcher_icons: ^0.14.4
  http: ^1.5.0
  google_sign_in: ^7.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/

flutter_launcher_icons:
  android: true
  ios: true
  image_path: 'assets/images/icon.png'
  web:
    generate: true
    image_path: 'assets/images/icon.png'
    min_size: 48
    max_size: 512
    background_color: '#ffffff'
    remove_alpha_ios: true
    adaptive_icon_background: '#ffffff'
    adaptive_icon_foreground: 'assets/images/icon.png'
  windows:
    generate: true
    image_path: 'assets/images/icon.png'
    background_color: '#ffffff'
  macos:
    generate: true
    image_path: 'assets/images/icon.png'
    background_color: '#ffffff'
  linux:
    generate: true
    image_path: 'assets/images/icon.png'
    background_color: '#ffffff'
  flavor:
    dev:
      android: true
      ios: true
      image_path: 'assets/images/icon-dev.png'
    prod:
      android: true
      ios: true
      image_path: 'assets/images/icon.png'
    staging:
      android: true
      ios: true
      image_path: 'assets/images/icon-staging.png'
